### ISSUE TITLE
Keypoints Dataset - flip_keypoint,missing size issue

### ISSUE THREAD

**Issue by kkoripl** [DonsetPG/narya#12]
Hi,

During training phase for keypoints just after reading them from .xml files there is a method invoked on every loaded keypoint to flip it (utils.masks.py):
```
def _flip_keypoint(id_kp, x_kp, y_kp, input_shape=(320, 320, 3))
```
In general it takes 4 arguments: keypoints id, x, y and.. size of an image. But keypoints_dataset class call to this method is missing this last one, that is why every single time images used to train keypoints model need to be in 320x320x3 format:
```
for id_kp, v in six.iteritems(keypoints):
    new_id_kp, x_kp, y_kp = _flip_keypoint(id_kp, min(v[0],image.shape[0]-1), min(v[1],image.shape[1]-1))
    new_keypoints[new_id_kp] = (x_kp, y_kp)
```
Think this call should be made like that or there will be no possibility to train model on differently sized pictures:
```
for id_kp, v in six.iteritems(keypoints):
    new_id_kp, x_kp, y_kp = _flip_keypoint(id_kp, min(v[0],image.shape[0]-1), min(v[1],image.shape[1]-1), image.shape)
    new_keypoints[new_id_kp] = (x_kp, y_kp)
```

**Comment by DonsetPG** [comment]
Hey,

This is resolved in the following [commit](https://github.com/DonsetPG/narya/commit/9e108d40fed4a13801c5e2f80fa673758c438450). 

I also changed two functions where the same problem might happen in the future.

Some shapes are still hardcoded in the ```PlayerBallTracker``` class but that should not cause any issues.

Thanks
