### ISSUE TITLE
full-tracking.ipynb colab crashes

### ISSUE THREAD

**Issue by alen1010** [DonsetPG/narya#21]
Hi,
I'm trying to run full-tracking.ipynb and every time I run this cell:
`tracker = FootballTracker(frame_rate=24.7,track_buffer = 60)`
the notebook just crashes and restarts, only error I can get is app.log
`{"name":"app","hostname":"0272c32279bc","pid":1,"type":"jupyter","level":30,"msg":"The Jupyter Notebook is running at:","time":"2021-02-23T20:01:27.113Z","v":0}
{"name":"app","hostname":"0272c32279bc","pid":1,"type":"jupyter","level":30,"msg":"http://172.28.0.12:9000/","time":"2021-02-23T20:01:27.114Z","v":0}
{"name":"app","hostname":"0272c32279bc","pid":1,"type":"jupyter","level":30,"msg":"Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).","time":"2021-02-23T20:01:27.114Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"google.colab serverextension initialized.","time":"2021-02-23T20:01:27.111Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"Serving notebooks from local directory: /","time":"2021-02-23T20:01:27.115Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"0 active kernels","time":"2021-02-23T20:01:27.115Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"The Jupyter Notebook is running at:","time":"2021-02-23T20:01:27.115Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"http://172.28.0.2:9000/","time":"2021-02-23T20:01:27.115Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).","time":"2021-02-23T20:01:27.115Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"Kernel started: f1e57aae-7e38-0d90a92821e0","time":"2021-02-23T20:01:30.178Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"Adapting to protocol v5.1 for kernel f1e57aae-7e38-0d90a92821e0","time":"2021-02-23T20:01:31.374Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"Kernel restarted: f1e57aae-7e38-0d90a92821e0","time":"2021-02-23T20:08:30.051Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"[20:09:16] src/imperative/./imperative_utils.h:92: GPU support is disabled. Compile MXNet with USE_CUDA=1 to enable GPU support.","time":"2021-02-23T20:09:16.738Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"terminate called after throwing an instance of 'dmlc::Error'","time":"2021-02-23T20:09:16.739Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"  what():  [20:09:16] src/imperative/imperative.cc:81: Operator _zeros is not implemented for GPU.","time":"2021-02-23T20:09:16.739Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"Stack trace:","time":"2021-02-23T20:09:16.740Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"  [bt] (0) /usr/local/lib/python3.7/dist-packages/mxnet/libmxnet.so(+0x307d3b) [0x7f6cb840cd3b]","time":"2021-02-23T20:09:16.740Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"  [bt] (1) /usr/local/lib/python3.7/dist-packages/mxnet/libmxnet.so(mxnet::Imperative::InvokeOp(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode, mxnet::OpStatePtr)+0x6bb) [0x7f6cbb5aec5b]","time":"2021-02-23T20:09:16.740Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":30,"msg":"KernelRestarter: restarting kernel (1/5), keep random ports","time":"2021-02-23T20:09:18.050Z","v":0}
{"name":"app","hostname":"dd02dc2c4d71","pid":1,"type":"jupyter","level":40,"msg":"**WARNING:root:kernel f1e57aae-7e38-0d90a92821e0 restarted**","time":"2021-02-23T20:09:18.050Z","v":0}
`

**Comment by DonsetPG** [comment]
Hey,
If its on a colab, could you share a version? 
If not, could you give some details on the OS, the python and libraries versions you are using, etc. 

Thanks!

**Comment by alen1010** [comment]
I'm running it in colab.
Python version is 3.7.10
I install all requirements.txt libraries:
!pip install tensorflow==2.2.0
!pip install torch==1.5.0
!pip install torchvision==0.6.0
!pip install mxnet==1.6.0
!pip install gluoncv==0.7.0
!pip install Keras==2.3.1
!pip install segmentation-models==1.0.1
!pip install progressbar2==3.38.0
!pip install tensorflow-probability==0.11.0
!pip install dm-sonnet==2.0.0
!pip install opencv-python==4.2.0.34
!pip install Shapely==1.7.0
!pip install moviepy==1.0.2
!pip install kornia==0.3.1
!pip install lap==0.4.0
!pip install Cython==0.29.15
!pip install cython-bbox==0.1.3
!pip install pandas==0.25.3
colab runtime type: tried with Hardware accelerator: None and GPU -> same error

Don't know if this helps, but here are all the libraries installed (!pip list -v):
https://codeshare.io/2K31qE

**Comment by DonsetPG** [comment]
This [colab](https://colab.research.google.com/drive/16yMoUTdmbBjJmYvkmEdYC-i4rIqpE_LC?usp=sharing) version works fine. Let me know if it helps to solve your issue. 
Otherwise, please share a copy of the colab you currently use!

Thanks!

**Comment by alen1010** [comment]
I tried your colab and it works. 
The difference between full-tracking.ipynb and NaryaExampleClean_Tracker.ipynb is that you initialize FootballTracker with one more parameter:
full-tracking.ipynb (doesn't work):
`tracker = FootballTracker(frame_rate=24.7,track_buffer = 60)`

NaryaExampleClean_Tracker.ipynb (this works):
```
import mxnet as mx
ctx = [mx.cpu()]
tracker = FootballTracker(frame_rate=24.7,track_buffer = 60, ctx=ctx)
```
I tried running models_examples.ipynb and I'm getting the same problem (colab crashes and restarts) on line: tracker_model = TrackerModel(pretrained=True, backbone='ssd_512_resnet50_v1_coco'), adding import for ctx and passing it as a parameter solves the problem.

**Comment by DonsetPG** [comment]
Yes, that's my bad. I remember correcting that in the Colab and not in the notebooks. I'll try to push a correction asap.
