### ISSUE TITLE
Readme link - 404 Page not found

### ISSUE THREAD

**Issue by alen1010** [DonsetPG/narya#25]
README.md
_and released of blog post version of these notebooks here._
Link redirects to  https://donsetpg.github.io/blog/2020/08/20/Narya/, which doesn't exist.
You probably meant this: https://donsetpg.github.io/blog/2020/12/24/Narya/

**Comment by DonsetPG** [comment]
Fixed in [6ef2ceb
](https://github.com/DonsetPG/narya/commit/6ef2ceb861e4169394aa706577a5474be33f936f)

Thanks
