### ISSUE TITLE
Error in training keypoints

### ISSUE THREAD

**Issue by Rit-ctrl** [DonsetPG/narya#36]
I faced tuple index out of range error while training the keypoints model [line 111](https://github.com/DonsetPG/narya/blob/master/narya/trainer/keypoints_train.py).

![image](https://user-images.githubusercontent.com/53635318/120357076-ad603580-c322-11eb-8ce6-ffb7ff9f8ad5.png)

Here is the complete trace

https://gist.github.com/Rit-ctrl/13b448b1ac115297d1abf43db9f18eed

I get this error irrespective of the dataset I use for training

**Comment by DonsetPG** [comment]
Hey, can it be linked with [issues#35](https://github.com/DonsetPG/narya/issues/35) ? 

Could you try the solutions given by @alen1010 and see if this solve the issue?  Otherwise I'll try to investigate.

**Comment by Rit-ctrl** [comment]
> Hey, can it be linked with issues#35 ? 

Yeah sure.

> Could you try the solutions given by @alen1010 and see if this solve the issue? Otherwise I'll try to investigate.

Yeah I tried them. Still the same error arises

**Comment by DonsetPG** [comment]
I can't reproduce your error on my side. 
However, using solutions proposed in [issues#35](https://github.com/DonsetPG/narya/issues/35) and modifying [`class Dataloder(keras.utils.Sequence):`](https://github.com/DonsetPG/narya/blob/master/narya/datasets/keypoints_dataset.py#L145) to `tf.keras.utils.Sequence` let's me train the model.

**Comment by Rit-ctrl** [comment]
Would it be possible for you to share the Colab file which you used for testing now?
