### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by burakkaraceylan** [DonsetPG/narya#39]
Hello,

First of all thank you for this amazing work. I am interested in tracking players and projecting their coordinates on a 2D plane using live camera. I am not interested in the analysis part, just the projection. Could your detection, homography and reid models  be used with live video stream and achieve good fps performance?

**Comment by DonsetPG** [comment]
Hey, thanks for the message. Even with a GPU this is not possible at the moment, you will experience delay.

**Comment by burakkaraceylan** [comment]
Thank you for the answer.
