### ISSUE TITLE
Pitch keypoints id's description

### ISSUE THREAD

**Issue by kkoripl** [DonsetPG/narya#4]
Hi,

I'd like to train homography model with new key points data, so looked into your scripts for that thing and to data set. There are xml files with keypoints id's in there (29 of them or so). Are they same for every data set picture? I mean like is id = 0 every single time the middle of the pitch? Maybe could you make a graphic to show which id's are which points on the pitch?

**Comment by DonsetPG** [comment]
Hey @kkoripl

Yes, 29 keypoints and always at the same place for every picture. Here is an image with the keypoints and their id: 

![103840207_255531052421430_2272109832518248052_n-2](https://user-images.githubusercontent.com/44346877/106486988-83048580-64b2-11eb-9f5a-377e1b1115a2.png)

I hope that this is useful.

**Comment by kkoripl** [comment]
That's great! Thanks!

**Comment by kkoripl** [comment]
Two more questions:
- Do the keypoints in each .xml file need to be ordered by their id's (names) or can they be in random order?
- Do the images need to be in dimension of 320x320 for the model to learn or they can be in any? Maybe always square one? I'm just curious, why in dataset pictures are in different dimension than on the example notebooks, pictures used to find homographies at.

**Comment by DonsetPG** [comment]
Hey,

> Do the keypoints in each .xml file need to be ordered by their id's (names) or can they be in random order?

No, they can be in any order. 

> Do the images need to be in dimension of 320x320 for the model to learn or they can be in any? Maybe always square one? I'm just curious, why in dataset pictures are in different dimension than on the example notebooks, pictures used to find homographies at.


To train the model: you can set the dimension to whatever you want, but it needs to be the dimension of the images in the dataset, and the dimension of the keypoints annotations. 

However, once the model is trained, you can process images of any size. In a prediction pipeline, an image will be resized by the homography model before processing it and will then be resized back (and so will the predictions). 

I hope that's clear, let me know if you have any other questions.

**Comment by kkoripl** [comment]
Thanks for the info! I'm a little bit closer with creating data generator thanks to your feedback. Two more, this time about learning itself:
- I saw in train data set picture 3, where keypoint id 21 (right half lower 18yard box corner) is hidden by a player, but still got into xml file. What's the rule for this kind of an event? Should I add key points even if I don't see them on the picture (i.e. they're hidden by player, tv visualisation, whatever), but know where they are?
- Do I need to have +- same amount of every type of key points in all data set xml files or, can I have for instance 50 x id=0 and 3 x id=1 without major harm to training results?

**Comment by DonsetPG** [comment]
Hey,

> I saw in train data set picture 3, where keypoint id 21 (right half lower 18yard box corner) is hidden by a player, but still got into xml file. What's the rule for this kind of an event? Should I add key points even if I don't see them on the picture (i.e. they're hidden by player, tv visualisation, whatever), but know where they are?

In theory, you're supposed to keep the same rule throughout the dataset (label even hidden keypoints or not). I believe in general you should not label hidden objects, but since here the keypoints positions and camera angle are extremely correlated, I still decided to label them. 

Just chose one plan and stick to it.

> Do I need to have +- same amount of every type of key points in all data set xml files or, can I have for instance 50 x id=0 and 3 x id=1 without major harm to training results?

It's definitively better to have balanced classes. I don't remember the statistics for our dataset though.

**Comment by kkoripl** [comment]
One, more as it's connected to the training itself. 
I've just find out, that pictures need to be in .jpg format, as looking for corresponding .xml files in dataset is based on replacing one extension to the other. Why can't they be i.e. .png's?

**Comment by DonsetPG** [comment]
Hey, 
Yes I remember running into this issue while writing the script and training models myself. 
To be honest I have no idea why it's not possible haha

Let me know if you find an explanation or a solution!

**Comment by JefeDryden** [comment]
Just wanted to say that I've been able to run a training session for keypoints with .png's. 

What you need to do is change line 47 in narya\datasets\keypoints_dataset.py from:
os.path.join(masks_dir, image_id.replace(".jpg", ".xml"))

to:
os.path.join(masks_dir, image_id.replace(".png", ".xml"))

Hope this helps!

**Comment by DonsetPG** [comment]
Yes good catch, I should have checked the code back instead of using my memory haha. 

The problem is solved in the last [commit](https://github.com/DonsetPG/narya/commit/8977b4f79b930a1988f837f712153a0325712351). 

I replaced 
```python3
os.path.join(masks_dir, image_id.replace(".jpg", ".xml"))
```

by

```python3
os.path.join(masks_dir, os.path.splitext(image_id)[0] + ".xml")
```

Thanks!

**Comment by kkoripl** [comment]
Yep, this lines were the cause, why I was asking about it all, because didn't understand, why we're looking only on .jpg's.
And now I need to reverse last commit on generator. :P
