### ISSUE TITLE
Training time for KeypointDetectorModel

### ISSUE THREAD

**Issue by alenm10** [DonsetPG/narya#40]
Is there a reason why training KeypointDetectorModel is so much slower now?
I used to train on 100 epoch for about 3 hours few months ago in GoogleColab but now for just one epoch it takes about 40 minutes (67 hours for all 100 epochs).
Does anyone have a similar problem?

**Comment by alenm10** [comment]
Tried to run it on TPU in GoogleColab and it's 10 minutes per epoch which is faster than GPU but still 17 hours for 100 epochs.

**Comment by DonsetPG** [comment]
Hey, 

I have no idea, no modifications were made in Narya's code.
 
* Did you compare the GPU you got and the one you had before? 
* Is from changes that were made in the library we use? I am not sure why it would impact the speed of training though. 

Sorry I can't be more helpful.

**Comment by alenm10** [comment]
Hi @DonsetPG ,
I tried to copy the code from keypoints_dataset.py directly to notebook instead of using imports and I also didn't install all libraries from requirements.txt, I installed these two:
```
!pip install segmentation-models==1.0.1
!pip install --upgrade albumentations
```
And I have only this imported:
```
from glob import glob
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import datetime, os
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from lxml import etree
import six
import cv2
import random
import albumentations as A
import segmentation_models as sm
sm.set_framework('tf.keras')
sm.framework()
```

And it is back to 80 seconds per epoch. It could be that some of the installed libraries were slowing it down.

I also had a problem when training where the error would say that segmentation model expected different size for inputs and the way I solved it was to change line 174 in https://github.com/DonsetPG/narya/blob/master/narya/datasets/keypoints_dataset.py 
instead of `return batch` I used `return batch[0], batch[1]` and that solved the error. Don't know why :)

**Comment by Rit-ctrl** [comment]
@alen1010 Yeah i used return tuple(batch) and it worked for me as well. I saw the solution from here **https://github.com/qubvel/segmentation_models/issues/412**
