### ISSUE TITLE
GoogleAPI 403 error : API delinquent ? 

### ISSUE THREAD

**Issue by yoshi2210** [DonsetPG/narya#54]
I found that the code related to downloading the pre-trained model through googleapis.com didn't work today.
The error said 403 error and I wasn't able to access each data by accessing each URL.

I'm so afraid but I guess it's caused by the GCP license. Does anybody have any ideas?
I didn't download the pre-trained model, so I'm so glad to have weights not only as API but through GitHub or something to use.

## program error code
Exception: URL fetch failure on https://storage.googleapis.com/narya-bucket-1/models/deep_homo_model_1.h5: 403 -- Forbidden
Exception: URL fetch failure on https://storage.googleapis.com/narya-bucket-1/models/player_tracker.params: 403 -- Forbidde

## html page once I access each URL listed in https://donsetpg.github.io/naryaDoc/models/index.html

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>The project to be billed is associated with a delinquent billing account.</Message>
<Details>The billing account for the owning project is disabled in state delinquent</Details>
</Error>

**Comment by DonsetPG** [comment]
Hi,
Yes I think my card expired haha.
Will update that now and the system should resume a usable state.

Cheers

**Comment by jhkchan** [comment]
Hi @DonsetPG, I emailed you earlier about the same issue, but I still cannot access the models. Can you help check? Thank you very much!

**Comment by Sgabox** [comment]
Hi @DonsetPG , I opened another issue equal to this one, There is still the same problem i cannot access the models. Can you help me? Thanks very much
