### ISSUE TITLE
Application of DeepHomoModel to vertical pitches

### ISSUE THREAD

**Issue by larsmaurath** [DonsetPG/narya#6]
Hi,

I have been trying to train the DeepHomoModel to identify vertical pitches which was pretty straight forward with your excellent documentation. 

What I have noticed is that the training on vertical pitch data seems to be slower than for the horizontal pitch data you trained on in your paper. I have adapted "https://github.com/DonsetPG/narya/blob/master/narya/trainer/homography_train.py" to my new training data and also played around with the default pitch specs in "get_default_corners" to use a larger share of the image.

I have currently trained on around 400 images, but results are significantly worse than when I train the model on 400 horizontal images from your data set.

**Do you have any sense why the model may not work as well for vertical pitches?** Of course there may be many reasons why it doesn't train as well in my case, but wanted to see if you have any no-brainer reasons before I generate more training data.

Below one of the best results I could generate:

<img width="358" alt="narya_vert_pitch" src="https://user-images.githubusercontent.com/11316760/107277430-5d332f80-6a22-11eb-920f-e17ab5a49392.png">

Thanks a lot already!

**Comment by DonsetPG** [comment]
Hey @larsmaurath 
Thanks for your message. I appreciate it!

Regarding your question, 2 things to take into considerations in my opinion:

- for vertical pitches, the range of tomography you have will be much smaller than for horizontal pitches. Therefore, the model must be much more precise, and the slightest error will give you a much more different result. (I hope that's understandable) 
- camera heights will probably vary much more for vertical pitches than for horizontal ones, making the homography prediction much harder. 

You may try the keypoint detection (but you would need to label the dataset sadly), as @TheoGreg and I found out that it worked much better on these types of vertical (or very broad) pitches. 

I hope this is helpful.
Have a nice day

**Comment by larsmaurath** [comment]
Thanks a lot for the quick response. That was the kind of intuitive explanation that I was hoping for.
I will try to generate more training data and also focus on the keypoint detection.

**If you are interested:** I have adapted [BirdsPyView](https://github.com/rjtavares/BirdsPyView) to efficiently generate training data with just a few clicks per case (generates both the npy for the homography and the xml for the keypoints). If training with this data works out I am happy to share including the training data for vertical pitches.

![label](https://user-images.githubusercontent.com/11316760/107390396-a8524e80-6ac5-11eb-818e-60644446c5d7.gif)

**Comment by DonsetPG** [comment]
Wow that looks super cool! 
Let me know if I can be of any help to help to adapt it to Narya. 

Cheers

**Comment by TheoGreg** [comment]
Very nice for improving the labelling phase ! Thanks a lot @larsmaurath !

**Comment by larsmaurath** [comment]
Thanks, I'll keep you updated. My current fear is that my key point labeling is too noisy since this is optimized for ease-of-use, but I'll keep you updated. Also noticed that this was probably better suited for 'Discussions' not 'Issues' so feel free to close.

**Comment by DonsetPG** [comment]
> Thanks, I'll keep you updated.

Please do, this could be super helpful to many people!

Cheers
