### ISSUE TITLE
GOOGLE API 403 ERROR

### ISSUE THREAD

**Issue by Sgabox** [DonsetPG/narya#64]
Hi, when I'm trying to use your library as soon as I try to execute the tracker, during the data download it gives me back this error: ' URL fetch failure on https://storage.googleapis.com/narya-bucket-1/models/player_tracker.params: 403 -- Forbidden'.
Do you have the file to make me download it? Or can you just simply put them back on?
Thanks for your time

**Comment by Jumabek** [comment]
still same issue, maybe provide weights via github ?

**Comment by Sgabox** [comment]
It would be perfect, I don't have any idea how to contact @DonsetPG , github seems to be the only way. We have to be patience

**Comment by top-ix** [comment]
is there any way to generate those files from scratch? if we can't download them can we create them? Any suggestion?

**Comment by Abhipray04** [comment]
Any luck with this?

**Comment by DonsetPG** [comment]
Situation should be resolved !
