### ISSUE TITLE
Cannot download datasets and weights

### ISSUE THREAD

**Issue by softmurata** [DonsetPG/narya#66]
Thanks for your great work!
I want to use pretrained weights and datasets, but link is expiring.
Please share them for me?

**Comment by edugzlez** [comment]
I too am trying to get the datasets and weights, particularly those from Direct Homography.

I have not been able to contact @DonsetPG. Maybe @TheoGreg has them as well.

We are still waiting.... :S

**Comment by DonsetPG** [comment]
Hey @edugzlez @softmurata sorry for the late reply. 
I need to update some information on the GCP account linked with the datasets and the weights. 
Will try to take care of it tomorrow.

**Comment by DonsetPG** [comment]
It should be good now !
